package com.consync.model

import java.time.Instant

/**
 * A sync plan containing all actions to be performed.
 *
 * The plan is generated by comparing local files with the current
 * Confluence state and determining what operations are needed.
 */
data class SyncPlan(
    /** All sync actions in execution order */
    val actions: List<SyncAction>,
    /** When this plan was generated */
    val generatedAt: Instant = Instant.now(),
    /** Space key being synced to */
    val spaceKey: String,
    /** Root page ID in Confluence */
    val rootPageId: String?,
    /** Total number of local pages */
    val totalLocalPages: Int,
    /** Total number of existing Confluence pages */
    val totalConfluencePages: Int
) {
    /** Actions that will create new pages */
    val createActions: List<SyncAction> by lazy {
        actions.filter { it.type == SyncActionType.CREATE }
    }

    /** Actions that will update existing pages */
    val updateActions: List<SyncAction> by lazy {
        actions.filter { it.type == SyncActionType.UPDATE }
    }

    /** Actions that will delete pages */
    val deleteActions: List<SyncAction> by lazy {
        actions.filter { it.type == SyncActionType.DELETE }
    }

    /** Actions that will move pages */
    val moveActions: List<SyncAction> by lazy {
        actions.filter { it.type == SyncActionType.MOVE }
    }

    /** Actions that are skipped (no change needed) */
    val skipActions: List<SyncAction> by lazy {
        actions.filter { it.type == SyncActionType.SKIP }
    }

    /** Count of pages to create */
    val createCount: Int get() = createActions.size

    /** Count of pages to update */
    val updateCount: Int get() = updateActions.size

    /** Count of pages to delete */
    val deleteCount: Int get() = deleteActions.size

    /** Count of pages to move */
    val moveCount: Int get() = moveActions.size

    /** Count of pages to skip */
    val skipCount: Int get() = skipActions.size

    /** Total count of modifying actions */
    val modifyingCount: Int get() = createCount + updateCount + deleteCount + moveCount

    /** Check if there are any changes to sync */
    val hasChanges: Boolean get() = modifyingCount > 0

    /** Check if the plan is empty (no actions at all) */
    val isEmpty: Boolean get() = actions.isEmpty()

    /**
     * Get a summary of the sync plan.
     */
    fun summary(): String = buildString {
        appendLine("Sync Plan Summary")
        appendLine("=================")
        appendLine("Space: $spaceKey")
        appendLine("Generated: $generatedAt")
        appendLine()
        appendLine("Local pages: $totalLocalPages")
        appendLine("Confluence pages: $totalConfluencePages")
        appendLine()
        appendLine("Actions:")
        appendLine("  Create: $createCount")
        appendLine("  Update: $updateCount")
        appendLine("  Delete: $deleteCount")
        appendLine("  Move: $moveCount")
        appendLine("  Skip: $skipCount")
        appendLine()
        if (hasChanges) {
            appendLine("Total changes: $modifyingCount")
        } else {
            appendLine("No changes required - everything is in sync!")
        }
    }

    /**
     * Get detailed list of all actions.
     */
    fun details(): String = buildString {
        if (createActions.isNotEmpty()) {
            appendLine("Pages to CREATE:")
            createActions.forEach { appendLine("  + ${it.title} (${it.relativePath})") }
            appendLine()
        }
        if (updateActions.isNotEmpty()) {
            appendLine("Pages to UPDATE:")
            updateActions.forEach { appendLine("  ~ ${it.title} (${it.relativePath}) - ${it.reason}") }
            appendLine()
        }
        if (deleteActions.isNotEmpty()) {
            appendLine("Pages to DELETE:")
            deleteActions.forEach { appendLine("  - ${it.title}") }
            appendLine()
        }
        if (moveActions.isNotEmpty()) {
            appendLine("Pages to MOVE:")
            moveActions.forEach { appendLine("  > ${it.title} (${it.relativePath})") }
            appendLine()
        }
        if (skipActions.isNotEmpty() && skipCount <= 10) {
            appendLine("Pages UNCHANGED:")
            skipActions.forEach { appendLine("  = ${it.title}") }
        } else if (skipActions.isNotEmpty()) {
            appendLine("Pages UNCHANGED: $skipCount (not listed)")
        }
    }

    companion object {
        /**
         * Create an empty sync plan (nothing to do).
         */
        fun empty(spaceKey: String, rootPageId: String?) = SyncPlan(
            actions = emptyList(),
            spaceKey = spaceKey,
            rootPageId = rootPageId,
            totalLocalPages = 0,
            totalConfluencePages = 0
        )
    }
}
